resourcestring                                     {deutsch}

  hntClose='Verbindung trennen und beenden';
  hntStatusBar='Anzahl gesendeter Messages | Anzahl empfangener Messages received | Status';
  capTime='Zeit';
  hntTime='Datum/Zeit UTC aus Message SYSTEM_TIME (2)';
  capRecord='CSV aufzeichnen';
  hntRecord='Aufzeichnen der empfangenen Daten-Messages in eine CSV Datei als Hexadezimal Zahlen';
  capSensor='Sensordatei erzeugen';
  hntSensor='Daten-Messages in eine binäre Datei speichern. Das Format ist wie die Sensordateien im FlightLog';
  capWarning='Keine Garantie. Benutzung auf eigenes Risiko!';
  hntPowerCycle='Verbindung trennen, Kamera ausschalten, kurz warten,'+lineending+'Kamera wieder einschalten und Verbinden.';


  capSaveText='&Text speichern';
  hntSaveText='Die Textmessages in eine Textdatei speichern';
  capPort='USB-Ports suchen...';
  hntPort='Im Falle von Verbindungsproblemen USB-Kabel ziehen und Stecken.'+lineending+
          'Doppelklick um Portliste zu erneuern.';
  capConnect='Verbinden';
  hntConnect='Mit dem ausgewählten USB-Port verbinden';
  capDisConnect='Trennen';
  hntDisConnect='System vom USB-Port trennen';
  hntSpeed='Baudrate einstellen. Default 500000 sollte die neueren Kameras funktionieren.';
  capClose='Beenden';
  capDeleteText='&Text löschen';
  hntDeleteText='Die Message Liste leeren.';
  capCopySerial='Vehicle ID kopieren';
  hntCopySerial='Vehicle ID (Seriennummer) in die Zwischenablage kopieren.';
  capReboot='Reboot';
  hntReboot='Gimbal neu starten.';

  captsYGC='Gimbal Kalibrierung E90';
  captsFC='Steuerung als FlightController für CGO3+ (Demo)';
  capGimbalCali='Gimbalkalibrierung';
  hntGimbalCali='Gimbalkalibrierungsprozess wie von ST16 gestartet.'+lineending+
                'Kamera aus- und wieder einschalten nachdem die Kalibrierung fertig ist.';
  hntGPS='Global Positioning System, früher NAVSTAR GPS';
  hntGLONASS='Глоба́льная навигацио́нная спу́тниковая систе́ма (ГЛОНА́СС)';
  hntSBAS='Satellite Based Augmentation System'+lineending+
          'Eine Methode, um die Sytemattribute wie Präzision, Zuverlässigkeit und Verfügbarkeit zu verbessern.';
  capSystemTime='Systemzeit UTC';
  capNotUsed='Ungenutzt';
  hntNotUsed='Satelliten, die (noch) nicht für die Positionsbestimmung genutzt sind';
  capSatUsed='Benutzt für Pos';
  hntSatUsed='Satelliten, die für die Positionsbestimmung genutzt werden';
  hntBoottime='Zeit seit Booten des Systems';
  capVersion='SW Versionen';
  hntVersion='Lese die verschiedenen Softwareversionen vom Gimbal aus';
  capYGC_Type='Anzeige einer 2. Message';
  hntYGC_Type='Wähle die Message aus, die du in der 2. Tabelle anzeigen willst.'+lineending+
              'Channel data bleibt in den meisten Fällen leer. Dies ist eine seltene Message.';
  hntPanelRight='Gimbalkalibrierung. Lese dazu unbedingt die Anleitung. Der Prozess geht von oben nach unten.';
  capSerialNo='Seriennummer:';
  capCenter='Mitte';
  hntCenter='Setze zurück in neutrale Position (Mittelstellung)';
  titSaveText='Textmeldungen speichern...';

  rsSaved=' gespeichert';
  rsDisconnected='Getrennt';
  rsConnected='Verbunden';
  rsEnabled='Enabled';
  rsAvailable='verfügbar';
  rsNotMounted='nicht vorhanden';
  rsInUse='Satelliten in Benutzung';
  rsVisible='Sichtbare Satelliten';
  rsConfirm='Bitte bestätigen';
  rsTime='Zeit';
  rsTimeUTC='System time UTC';
  hntTempCali='Dies benötigt eine spezielle Prozedur. Führe das nur durch, wenn du genau weißt, was du tust!';

  errSensorsNotHealthy='Sensoren nicht in Ordnung!';
  errNoUSBport='Kein USB-Port verfügbar';

